### PR TITLE
Operator destagger maintains vcoords

### LINKED ISSUE #1: coordinates lost after destagger
* Icon Data Processing Incubator version:
* Python version:
* Operating System:

### Description

I have a data array, var,  with the following coordinates: 
```
  * time        (time) int64 8B 0
  * z           (z) int64 480B 1 2 3 4 5 6 7 8 9 ... 52 53 54 55 56 57 58 59 60
    lat         (y, x) float64 2MB 42.18 42.18 42.18 42.19 ... 50.13 50.13 50.13
    lon         (y, x) float64 2MB 0.8064 0.8331 0.8598 ... 17.43 17.46 17.49
    valid_time  (time) datetime64[ns] 8B 2016-03-14T20:00:00
    ref_time    datetime64[ns] 8B 2016-03-14T20:00:00
```
After applying destagger(var, "x"), many coordinates are lost. 

```
Coordinates:
  * time     (time) int64 8B 0
  * z        (z) int64 480B 1 2 3 4 5 6 7 8 9 10 ... 52 53 54 55 56 57 58 59 60
 ```

Shouldnt we retain whatever coordinates the input array brings ?

### PR DESCRIPTION
**Pull request by cfkanesan**
## Purpose

The destagger operator maintains the vertical coordinate. Closes #1

### CODE REVIEW

**Review by cosunae — CHANGES_REQUESTED** [review]
thanks @cfkanesan
The implementation looks correct to me, and the new z coordinates are tested. 

I think we should also test the grib metadata associated to the horizontal grid. 
I.e. the keys that are set in _update_grid.
And ideally, if possible also the grib metadata (level) associated to the z coordinate. Since a correct z coordinate does not guarantee a correct grib level metadata. That assuming it is possible to test the grib in memory (i.e. not writing to disk)

**Comment by cosunae** [comment]
Can you also fix the CD/CI tests ?

**Comment by cfkanesan** [comment]
> And ideally, if possible also the grib metadata (level) associated to the z coordinate. Since a correct z coordinate does not guarantee a correct grib level metadata. That assuming it is possible to test the grib in memory (i.e. not writing to disk)

The grib level is derived from the z coordinate in the `save` function. This functionality is covered by the existing test.

**Comment by cosunae** [comment]
> > And ideally, if possible also the grib metadata (level) associated to the z coordinate. Since a correct z coordinate does not guarantee a correct grib level metadata. That assuming it is possible to test the grib in memory (i.e. not writing to disk)
> 
> The grib level is derived from the z coordinate in the `save` function. This functionality is covered by the existing test.

Yes, I agree that the save test is the right place. The only issue is that the save is not testing the grib metadata (and removing the message explicitly after loading a save field). But it is constructing again another xarray from grib, so through several hops is probably testing the level of the metadata, which would go into the coordinate that is tested. So I guess it is fine

**Review by cosunae — APPROVED** [review]

**Pull request merged**
